### ISSUE TITLE
Move focus immediately on field change

### ISSUE THREAD

**Issue by jonny-no1** [fourlabsldn/fl-interactive-form#8]
When moving to the next field (using the tab key for example) the first few characters typed end up in the previously focused field. Typing should be possible even while the animation is still in progress.

**Comment by lazamar** [comment]
The order desired would be:
- focus next
- animate validation
- animate slide

This is not very easy to accomplish because the sliding and focusing the next element are taken care of by the same function `goToField` while the validation animation, the one keeping the focus, is taken care of by the input field itself. So, even though the ordering can change, focusing and sliding must happen together.

This animation only happens when the field is being validated for the first time.
The feasible options are:
- Keep it the way it is
- Move to the next field immediately, and not wait for the animation

**Comment by jonny-no1** [comment]
How about:
- Animate validation feedback
- Focus next
- Animate slide

**Comment by lazamar** [comment]
That is how it currently is. The problem is the fact that animate validation takes 500 milliseconds.

**Comment by jonny-no1** [comment]
Animation time reduced to 200 ms in 86d230bfbbbe8e12de4ea1398b126ab46237f2ed.
